# Replace the text below to customize your site
site_name: IHG — MDEF # - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Ivan Hunga Garcia
copyright: # Copyleft 2023 "Ivan Garcia" - GNU Free Documentation License
repo_name: 'IHG — MDEF'
site_url: https://ivan-miguez.github.io/mdef
repo_url: 'https://github.com/ivan-miguez/mdef'


nav:
  - Home: index.md
  - About: about/me.md
  - Biotic Skin:
      - Process: project/project.md
      - Case Study: "project/case study.md"
      - Research Question: term2/Research Question.md
  - Deliverables :
      - Term 1:
          - Bootcamp: term1/Bootcamp.md
          - AoWS: term1/Atlas of Weak Signals.md
          - "Design Studio I": 
              - "Embodied Criticism": term1/Design Studio I/embodied criticism.md
          - "Living with your own ideas": term1/Living with your own ideas.md
          - "(Fun)damentals for Future Makers": term1/(fun)damentals for Future Makers.md
          - "Unpacking Tech Systems": 
            - "Reflection and Zine": term1/Unpacking Tech Systems/Reflection and Zine.md
            - "Forensic Report - Apple Macbook": term1/Unpacking Tech Systems/Forensic Report - Apple Macbook.md
            - Inventory: 'https://docs.google.com/spreadsheets/d/1nhxFCAaLnu5iB0xfygtxfu7oa6Qrs6oYqWyNHF1m7AE/edit?gid=0#gid=0)'
            - "The Meluza Machine": 'https://docs.google.com/presentation/d/1yEwyA1XbDtHeK4ixy4tmtcUPgdfOU9xSFolHBjHSZMg/edit?slide=id.g3aa21e6ebb2_0_149#slide=id.g3aa21e6ebb2_0_149)'
            - Video: 'https://drive.google.com/file/d/1ufmgwQTAlXusmx9v1ZrRUB4JBQTVwE7E/view?usp=drive_link'
          - "Designing with others": term1/Narratives II/Designing with Others.md
          - "Extended Inteligences I": 
            - "What Sticks": term1/Extended Inteligences I/What Sticks.md
            - "Personal Manifesto": term1/Extended Inteligences I/Personal Manifesto.md
          - "Narratives I": 
            - "Pictorial Draft": term1/Narratives I/Pictorial Draft.md

     
      - Term 2:
          - digi: term1/Bootcamp.md
          - studio: term1/Bootcamp.md


theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: grey
    accent: grey
  font:
    # See available fonts at https://fonts.google.com/
    text: Averia Serif Libre
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
